"Added Footer section"
gdscsmit/gdscsmit.github.io pull request #80
Opened 2023-10-17 16:44 UTC by falgun143

Solves issues #29 .Please review it .

2023-10-17 17:08 UTC, pooranjoyb commented on src/Components/Footer.jsx
> +            <FaFacebookF style={{ color: "#1A6ED8",marginBottom:"15px" }}></FaFacebookF>
`GDSC-SMIT` isn't in Facebook, please update the same with Instagram.

2023-10-17 17:08 UTC, pooranjoyb commented on src/Components/Footer.jsx
> +          <Youtube
Also, please remove Youtube :/

2023-10-17 17:09 UTC, pooranjoyb commented on src/Components/Footer.jsx
> +        <h4>© 2023 COPYRIGHT GDSC SMIT</h4>
Reduce the size of this text :)

2023-10-17 17:11 UTC, pooranjoyb commented on src/Components/Footer.jsx
> +        <div>
### Remove these content : 

![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/90945182/38295e84-1e99-4259-8a06-f8c01b7600ae)
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/90945182/070c806e-e845-4f21-bccb-64e7ec79853c)

2023-10-17 17:12 UTC, pooranjoyb requested changes
Please also reduce the size of Brand Icons and make sure they're responsive in smaller screens.

2023-10-18 05:27 UTC, falgun143 commented
@pooranjoyb Sure ,I will make the changes and give you the update.

2023-10-18 14:04 UTC, pooranjoyb commented
> @pooranjoyb Can you give me the link for the instagram and also tell me that .After removing about and help section what should i put there can i do something like this or remove this one also. ![image](https://user-images.githubusercontent.com/105922142/276259610-d44c09a7-e85c-4595-b140-f633bb670df3.png)

Nope, just make it minimalistic :) @falgun143

2023-10-18 17:22 UTC, falgun143 commented
@pooranjoyb  please review it.

2023-10-19 04:59 UTC, pooranjoyb approved these changes

2023-10-19 05:00 UTC, merged